# Use the official Nginx image
FROM nginx:alpine

# # Copy custom Nginx configuration
# COPY default.conf /etc/nginx/conf.d/default.conf

# Copy the static index.html into the web root
COPY index.html /usr/share/nginx/html/index.html

# Expose port 80
EXPOSE 80

# Start Nginx in the foreground
CMD ["nginx", "-g", "daemon off;"]
